"""
Session device tracking and refresh token management
SECURITY: Device-based session management + token rotation
"""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, Boolean, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.core.database import Base


class SessionDevice(Base):
    """
    Track user sessions per device
    Enables "logout all devices" functionality
    """
    __tablename__ = "session_devices"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Device identification
    device_id = Column(String(255), nullable=False, unique=True, index=True)  # UUID generated by client
    device_type = Column(String(50), nullable=True)  # mobile, tablet, desktop
    os = Column(String(100), nullable=True)
    browser = Column(String(100), nullable=True)
    ip_address = Column(String(45), nullable=True)  # IPv4 or IPv6
    
    # Session tracking
    last_active_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False, index=True)
    
    # Relationships
    user = relationship("User", back_populates="session_devices")
    refresh_tokens = relationship("RefreshToken", back_populates="session_device", cascade="all, delete-orphan")


class RefreshToken(Base):
    """
    Rotating refresh tokens with reuse detection
    SECURITY: Store hash of token, not plain text
    """
    __tablename__ = "refresh_tokens"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    device_id = Column(String(255), ForeignKey("session_devices.device_id", ondelete="CASCADE"), nullable=False, index=True)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Token storage (SECURITY: Store hash, not plain text)
    token_hash = Column(String(64), nullable=False, unique=True, index=True)  # SHA-256 hash
    
    # Token metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    expires_at = Column(DateTime, nullable=False, index=True)
    last_used_at = Column(DateTime, nullable=True)
    
    # Token rotation
    is_valid = Column(Boolean, default=True, nullable=False, index=True)
    replaced_by = Column(UUID(as_uuid=True), ForeignKey("refresh_tokens.id", ondelete="SET NULL"), nullable=True)
    
    # Relationships
    user = relationship("User", back_populates="refresh_tokens")
    session_device = relationship("SessionDevice", back_populates="refresh_tokens")
